/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitStoreRouteImport } from './routes/visit-store'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as CustomStitchingRouteImport } from './routes/custom-stitching'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'

const VisitStoreRoute = VisitStoreRouteImport.update({
  id: '/visit-store',
  path: '/visit-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomStitchingRoute = CustomStitchingRouteImport.update({
  id: '/custom-stitching',
  path: '/custom-stitching',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/custom-stitching': typeof CustomStitchingRoute
  '/lookbook': typeof LookbookRoute
  '/shop': typeof ShopRoute
  '/visit-store': typeof VisitStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/custom-stitching': typeof CustomStitchingRoute
  '/lookbook': typeof LookbookRoute
  '/shop': typeof ShopRoute
  '/visit-store': typeof VisitStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/custom-stitching': typeof CustomStitchingRoute
  '/lookbook': typeof LookbookRoute
  '/shop': typeof ShopRoute
  '/visit-store': typeof VisitStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/contact'
    | '/custom-stitching'
    | '/lookbook'
    | '/shop'
    | '/visit-store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/contact'
    | '/custom-stitching'
    | '/lookbook'
    | '/shop'
    | '/visit-store'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/contact'
    | '/custom-stitching'
    | '/lookbook'
    | '/shop'
    | '/visit-store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  CustomStitchingRoute: typeof CustomStitchingRoute
  LookbookRoute: typeof LookbookRoute
  ShopRoute: typeof ShopRoute
  VisitStoreRoute: typeof VisitStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit-store': {
      id: '/visit-store'
      path: '/visit-store'
      fullPath: '/visit-store'
      preLoaderRoute: typeof VisitStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-stitching': {
      id: '/custom-stitching'
      path: '/custom-stitching'
      fullPath: '/custom-stitching'
      preLoaderRoute: typeof CustomStitchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  CustomStitchingRoute: CustomStitchingRoute,
  LookbookRoute: LookbookRoute,
  ShopRoute: ShopRoute,
  VisitStoreRoute: VisitStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
